"""make fields nullable

Revision ID: c12879368caf
Revises: d5aa39bbeb48
Create Date: 2024-05-23 22:14:34.339296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c12879368caf'
down_revision = 'd5aa39bbeb48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.alter_column('budget_amount',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('withdraw_category',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('withdraw_description',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('withdraw_amount',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.alter_column('withdraw_amount',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('withdraw_description',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('withdraw_category',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('budget_amount',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
